[package]
name = "command"
version = "0.1.0"
authors = ["Sebastian Waisbrot <seppo0010@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "2"
rand = "0.8"
mlua = { version = "0.9", features = ["lua54", "vendored"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
compat = { path = "../compat" }
config = { path = "../config" }
database = { path = "../database" }
logger = { path = "../logger" }
parser = { path = "../parser" }
response = { path = "../response" }
util = { path = "../util" }
