[package]
name = "networking"
version = "0.1.0"
authors = ["Sebastian Waisbrot <seppo0010@gmail.com>"]
edition = "2018"

[dependencies.config]
path = "../config"

[dependencies.logger]
path = "../logger"

[dependencies.util]
path = "../util"

[dependencies.parser]
path = "../parser"

[dependencies.response]
path = "../response"

[dependencies.database]
path = "../database"

[dependencies.command]
path = "../command"

[dependencies]
bytes = "1"
libc = "0.2"
socket2 = "0.5"

[dependencies.persistence]
path = "../persistence"
