[package]
authors = ["Sebastian Waisbrot <seppo0010@gmail.com>"]
name = "database"
version = "0.1.0"

[dependencies]
ahash = "0.8"
crc64 = "2.0"
rand = "0.8"
skiplist = "1.1"
basichll = "0.3"
serde_json = { version = "1.0", features = ["preserve_order"] }

[dependencies.config]
path = "../config"

[dependencies.logger]
path = "../logger"

[dependencies.parser]
path = "../parser"

[dependencies.persistence]
path = "../persistence"

[dependencies.rdbutil]
path = "./rdbutil"

[dependencies.response]
path = "../response"

[dependencies.util]
path = "../util"
